package com.examples.discovery.main;

import com.examples.discovery.MyJnrTest;
import com.examples.discovery.MyJnrTest2;
import com.examples.discovery.subpackage.MyConcreteJnrTest;
import io.github.lorenzobettini.jnrtest.core.JnrTestConsoleExecutor;
import io.github.lorenzobettini.jnrtest.core.JnrTestRunner;

/**
 * This class is generated by the JnrTestMainGenerator tool.
 */
public class JnrTestMainGenerated {
	public static void fillTestRunner(JnrTestRunner runner) {
		runner.add(new MyJnrTest());
		runner.add(new MyJnrTest2());
		runner.add(new MyConcreteJnrTest());
	}

	public static void main(String[] args) {
		var executor = new JnrTestConsoleExecutor() {
			@Override
			protected JnrTestRunner createTestRunner() {
				var runner = new JnrTestRunner();
				JnrTestMainGenerated.fillTestRunner(runner);
				return runner;
			}
		};
		executor.execute();
	}
}
