package com.examplesdelegated.tests;

/**
 * Main class to run all generated JnrTest classes.
 * Automatically generated by JnrTestJUnitProcessor.
 */
public class JnrTestMain {

	public static void main(String[] args) {
		var executor = new io.github.lorenzobettini.jnrtest.core.JnrTestConsoleExecutor();
		executor.getReporter().withOnlySummaries();

		executor.add(new com.examplesdelegated.tests.ExampleTest2ClassJnrTest());
		executor.add(new com.examplesdelegated.tests.ExampleTestClassJnrTest());

		executor.execute();
	}
}
