package io.github.lorenzobettini.jnrtest.tools;

import java.io.IOException;
import java.nio.file.Path;

import javax.lang.model.element.Modifier;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;

import io.github.lorenzobettini.jnrtest.core.JnrTestConsoleExecutor;
import io.github.lorenzobettini.jnrtest.core.JnrTestRunner;

public class JnrTestMainGenerator {

	/**
	 * @param srcDir the source directory where to find the JnrTest subclasses
	 * @param outputDir the output directory where to generate the main class
	 * @param outputClass the fully qualified name of the output main class to generate
	 * @throws IOException 
	 */
	public void generateMain(String srcDir, String outputDir, String outputClass) throws IOException {
		var jnrTestInstnatiableClasses = new JnrTestDiscovery().discover(srcDir);
		
		// Extract package and class name from outputClass
		var lastDot = outputClass.lastIndexOf('.');
		var packageName = outputClass.substring(0, lastDot);
		var className = outputClass.substring(lastDot + 1);
		
		// Build the fillTestRunner method
		var fillTestRunnerMethod = MethodSpec.methodBuilder("fillTestRunner")
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC)
				.addParameter(JnrTestRunner.class, "runner")
				.returns(void.class);
		
		for (String testClass : jnrTestInstnatiableClasses) {
			fillTestRunnerMethod.addStatement("runner.add(new $T())", ClassName.bestGuess(testClass));
		}
		
		// Build the main method with anonymous class
		var mainMethodCode = CodeBlock.builder()
				.add("var executor = new $T() {\n", JnrTestConsoleExecutor.class)
				.indent()
				.add("@Override\n")
				.add("protected $T createTestRunner() {\n", JnrTestRunner.class)
				.indent()
				.addStatement("var runner = new $T()", JnrTestRunner.class)
				.addStatement("$L.fillTestRunner(runner)", className)
				.addStatement("return runner")
				.unindent()
				.add("}\n")
				.unindent()
				.add("};\n")
				.addStatement("executor.execute()")
				.build();
		
		var mainMethod = MethodSpec.methodBuilder("main")
				.addModifiers(Modifier.PUBLIC, Modifier.STATIC)
				.addParameter(String[].class, "args")
				.returns(void.class)
				.addCode(mainMethodCode)
				.build();
		
		// Build the class
		var generatedClass = TypeSpec.classBuilder(className)
				.addModifiers(Modifier.PUBLIC)
				.addJavadoc("This class is generated by the JnrTestMainGenerator tool.\n")
				.addMethod(fillTestRunnerMethod.build())
				.addMethod(mainMethod)
				.build();
		
		// Generate the Java file
		var javaFile = JavaFile.builder(packageName, generatedClass)
				.indent("\t")
				.skipJavaLangImports(true)
				.build();
		
		// Write to the output directory
		javaFile.writeTo(Path.of(outputDir));
	}

}
