package io.github.lorenzobettini.jnrtest.core;

/**
 * This class is generated by the JnrTestMainGenerator tool.
 */
public class JnrTestMainGenerated {
	public static void fillTestRunner(JnrTestRunner runner) {
		runner.add(new JnrTestConsoleExecutorTestJnrTest());
		runner.add(new JnrTestConsoleParallelExecutorTestJnrTest());
		runner.add(new JnrTestConsoleReporterTestJnrTest());
		runner.add(new JnrTestFilterTestJnrTest());
		runner.add(new JnrTestFiltersTestJnrTest());
		runner.add(new JnrTestParallelRunnerTestJnrTest());
		runner.add(new JnrTestRecorderTestJnrTest());
		runner.add(new JnrTestReporterInterfaceTestJnrTest());
		runner.add(new JnrTestRunnerTestJnrTest());
		runner.add(new JnrTestStatisticsTestJnrTest());
		runner.add(new JnrTestThreadSafeConsoleReporterTestJnrTest());
		runner.add(new JnrTestThreadSafeRecorderTestJnrTest());
	}

	public static void main(String[] args) {
		var executor = new JnrTestConsoleExecutor() {
			@Override
			protected JnrTestRunner createTestRunner() {
				var runner = new JnrTestRunner();
				JnrTestMainGenerated.fillTestRunner(runner);
				return runner;
			}
		};
		executor.execute();
	}
}
