package io.github.lorenzobettini.jnrtest.core;

/**
 * Main class to run all generated JnrTest classes.
 * Automatically generated by JnrTestJUnitProcessor.
 */
public class JnrTestMain {

	public static void main(String[] args) {
		var executor = new JnrTestConsoleExecutor();

		executor.testCase(new io.github.lorenzobettini.jnrtest.core.JnrTestThreadSafeRecorderTestJnrTest());
		executor.testCase(new io.github.lorenzobettini.jnrtest.core.JnrTestParallelRunnerTestJnrTest());
		executor.testCase(new io.github.lorenzobettini.jnrtest.core.JnrTestRunnerTestJnrTest());
		executor.testCase(new io.github.lorenzobettini.jnrtest.core.JnrTestConsoleReporterTestJnrTest());
		executor.testCase(new io.github.lorenzobettini.jnrtest.core.JnrTestThreadSafeConsoleReporterTestJnrTest());
		executor.testCase(new io.github.lorenzobettini.jnrtest.core.JnrTestConsoleExecutorTestJnrTest());
		executor.testCase(new io.github.lorenzobettini.jnrtest.core.JnrTestConsoleParallelExecutorTestJnrTest());

		executor.execute();
	}
}
