package io.github.lorenzobettini.jnrtest.core;

/**
 * Main class to run all generated JnrTest classes.
 * Automatically generated by JnrTestJUnitProcessor.
 */
public class JnrTestMain {

	public static void main(String[] args) {
		var executor = new JnrTestConsoleExecutor() {
			@Override
			protected JnrTestRunner createTestRunner() {
				var runner = new JnrTestRunner();
				JnrTestMainGenerated.fillTestRunner(runner);
				return runner;
			}
		};
		executor.getReporter().withOnlySummaries();

		executor.execute();
	}
}
